name: CI

on:
  push: {}

jobs:
  stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Composer
        run: composer install

      - name: Stan
        run: vendor/bin/phpstan analyse

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Composer
        run: composer install

      - name: Tests
        run: cd tests && ../vendor/bin/phpunit

  release:
    runs-on: ubuntu-latest
    needs: [stan, test]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}